# Exploring detail London airbnb listings

# Setup and load

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/listings.csv")

In [3]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11551,https://www.airbnb.com/rooms/11551,20260619061251,2026-06-25,city scrape,Artistic London Pied-à-Terre,Live like a local in this quintessential Londo...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,43039,...,4.84,4.54,4.49,NaN,NaN,1,1,0,0,0.99
1,13913,https://www.airbnb.com/rooms/13913,20260619061251,2026-06-25,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.88,4.79,4.79,NaN,NaN,2,1,1,0,0.30
2,15400,https://www.airbnb.com/rooms/15400,20260619061251,2026-06-26,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,NaN,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.94,4.74,NaN,NaN,1,1,0,0,0.49
3,17402,https://www.airbnb.com/rooms/17402,20260619061251,2026-06-29,city scrape,Spacious Fitzrovia 3bed/2bath By Soho & Oxford St,"Stay in this spacious 3-bedroom, 2-bath apartm...",NaN,https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.73,4.89,4.62,NaN,NaN,2,2,0,0,0.31
4,513198,https://www.airbnb.com/rooms/513198,20260619061251,2026-06-29,city scrape,Stunning views over Central London! (room),Wake up to the sound of Big Ben!<br /><br />Th...,NaN,https://a0.muscache.com/pictures/6442310/e4b3e...,2528030,...,4.74,4.72,4.42,NaN,NaN,2,1,1,0,0.25

In [5]:
df.shape

(92638, 90)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92638 entries, 0 to 92637
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            92638 non-null  int64
 1   listing_url                                   92638 non-null  str
 2   scrape_id                                     92638 non-null  int64
 3   last_scraped                                  92638 non-null  str
 4   source                                        92638 non-null  str
 5   name                                          92638 non-null  str
 6   description                                   90549 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   92633 non-null  str
 9   host_id                                       92638 non-null  int64
 10  host_url                                      92638 non-null  str
 11  host_profile_id                               92562 non-null  float64
 12  host_profile_url                              92554 non-null  str
 13  host_name                                     92562 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      92562 non-null  float64
 16  hosts_time_as_user_months                     92562 non-null  float64
 17  hosts_time_as_host_years                      92561 non-null  float64
 18  hosts_time_as_host_months                     92561 non-null  float64
 19  host_location                                 69928 non-null  str
 20  host_about                                    49229 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             92562 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              92562 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           92562 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          92562 non-null  str
 32  host_identity_verified                        92562 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        92638 non-null  str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      92638 non-null  float64
 37  longitude                                     92638 non-null  float64
 38  property_type                                 92638 non-null  str
 39  room_type                                     92638 non-null  str
 40  accommodates                                  92638 non-null  int64
 41  bathrooms                                     57762 non-null  float64
 42  bathrooms_text                                92504 non-null  str
 43  bedrooms                                      68655 non-null  float64
 44  beds                                          60163 non-null  float64
 45  amenities                                     92638 non-null  str
 46  price                                         62240 non-null  str
 47  price_quote_checkin_date                      64771 non-null  str
 48  price_quote_checkout_date                     64771 non-null  str
 49  price_quote_total_price                       62240 non-null  float64
 50  price_quote_price_per_night                   62240 non-null  float64
 51  price_quote_raw                               64771 non-null  str
 52  minimum_nights                                92633 non-null  float64
 53  maximum_nights                                92633 non-null  float64
 54  minimum_minimum_nights                        92633 non-null  float64
 55  maximum_minimum_nights                        92633 non-null  float64
 56  minimum_maximum_nights                        92633 non-null  float64
 57  maximum_maximum_nights                        92633 non-null  float64
 58  minimum_nights_avg_ntm                        92638 non-null  float64
 59  maximum_nights_avg_ntm                        92638 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              91778 non-null  str
 62  availability_30                               92638 non-null  int64
 63  availability_60                               92638 non-null  int64
 64  availability_90                               92638 non-null  int64
 65  availability_365                              92638 non-null  int64
 66  calendar_last_scraped                         92638 non-null  str
 67  number_of_reviews                             92638 non-null  int64
 68  number_of_reviews_ltm                         92638 non-null  int64
 69  number_of_reviews_l30d                        92638 non-null  int64
 70  availability_eoy                              92638 non-null  int64
 71  number_of_reviews_ly                          92638 non-null  int64
 72  estimated_occupancy_l365d                     92638 non-null  int64
 73  estimated_revenue_l365d                       62240 non-null  float64
 74  first_review                                  70711 non-null  str
 75  last_review                                   70711 non-null  str
 76  review_scores_rating                          70711 non-null  float64
 77  review_scores_accuracy                        70697 non-null  float64
 78  review_scores_cleanliness                     70702 non-null  float64
 79  review_scores_checkin                         70673 non-null  float64
 80  review_scores_communication                   70692 non-null  float64
 81  review_scores_location                        70672 non-null  float64
 82  review_scores_value                           70672 non-null  float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                92638 non-null  int64
 86  calculated_host_listings_count_entire_homes   92638 non-null  int64
 87  calculated_host_listings_count_private_rooms  92638 non-null  int64
 88  calculated_host_listings_count_shared_rooms   92638 non-null  int64
 89  reviews_per_month                             70711 non-null  float64
dtypes: float64(44), int64(18), str(28)
memory usage: 244.9 MB

In [9]:
df.isna().sum()

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
                                                ...
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                               21927
Length: 90, dtype: int64

In [10]:
df.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,9.263800e+04,9.263800e+04,0.0,9.263800e+04,9.256200e+04,0.0,92562.000000,92562.000000,92561.000000,92561.000000,...,70692.000000,70672.000000,70672.000000,0.0,0.0,92638.000000,92638.000000,92638.000000,92638.000000,70711.000000
mean,8.174866e+17,2.026062e+13,NaN,1.361402e+16,1.475942e+18,NaN,7.670037,5.454539,5.556023,5.400352,...,4.818871,4.741178,4.628688,NaN,NaN,16.402599,13.988547,2.248343,0.028843,0.987125
std,6.546986e+17,0.000000e+00,NaN,1.508990e+17,3.845402e+16,NaN,4.120067,3.554372,3.979819,3.594906,...,0.414242,0.394309,0.495310,NaN,NaN,49.874854,48.925545,9.551793,0.649517,1.317630
min,1.155100e+04,2.026062e+13,NaN,2.594000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.540656e+07,2.026062e+13,NaN,2.788031e+07,1.463035e+18,NaN,4.000000,2.000000,2.000000,2.000000,...,4.800000,4.670000,4.500000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.140000
50%,9.688296e+17,2.026062e+13,NaN,1.241214e+08,1.466998e+18,NaN,9.000000,5.000000,6.000000,5.000000,...,4.960000,4.850000,4.750000,NaN,NaN,2.000000,1.000000,0.000000,0.000000,0.490000
75%,1.425415e+18,2.026062e+13,NaN,4.468202e+08,1.470005e+18,NaN,11.000000,9.000000,9.000000,9.000000,...,5.000000,5.000000,4.930000,NaN,NaN,9.000000,6.000000,1.000000,0.000000,1.280000
max,1.710934e+18,2.026062e+13,NaN,1.710839e+18,1.710853e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,NaN,NaN,501.000000,500.000000,142.000000,25.000000,32.170000

In [ ]:

df[["price"]].sample(10)

         price
17608  $372.80
13895      NaN
23523      NaN
37059      NaN
52723  $146.00
84679  $400.00
5290       NaN
408     $41.00
68178  $117.86
92342  $439.00

In [ ]:
# testing pull request